import argparse
# TODO 修改路径
parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=234, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=14, type=int)

parser.add_argument('--max-epoch', default=15, type=int)
parser.add_argument('--model-path', default='/export/space0/qiu-y/result/vad_ucf/20250910_test/model_ucf.pth')
# parser.add_argument('--cur-path', default='/aidata/qiuyc/results/MTC-VAD/model_cur.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='/export/space0/qiu-y/result/vad_ucf/20250910_test/checkpoint.pth')
parser.add_argument('--batch-size', default=64, type=int)
parser.add_argument('--train-list', default='list/ucf_CLIP_rgb_yanai.csv')
# parser.add_argument('--train-list', default='list/ucf_CLIP_rgb_L40S.csv')
parser.add_argument('--test-list', default='list/ucf_CLIP_rgbtest_yanai.csv')
# parser.add_argument('--test-list', default='list/ucf_CLIP_rgbtest_L40S.csv')
parser.add_argument('--gt-path', default='list/gt_ucf.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment_ucf.npy')
parser.add_argument('--gt-label-path', default='list/gt_label_ucf.npy')

parser.add_argument('--lr', default=2e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[4, 8])